superlogin_auth:
    path:      /contao/superlogin/auth/{serverId}
    defaults:  { _controller: ComoloSuperLoginClientBundle:Authorization:authorization }

superlogin_auth_redirect:
    path:      /contao/superlogin/redirect/{serverId}
    defaults:  { _controller: ComoloSuperLoginClientBundle:Authorization:redirect }

# TODO: remove
superlogin_auth_debug:
    path:      /debug
    defaults:  { _controller: ComoloSuperLoginClientBundle:Authorization:debug }
