superlogin_auth:
    path:      /contao/superlogin/auth/{serverId}
    controller: Comolo\SuperLoginClient\ContaoEdition\Controller\AuthorizationController::authorization

superlogin_auth_redirect:
    path:      /contao/superlogin/redirect/{serverId}
    controller: Comolo\SuperLoginClient\ContaoEdition\Controller\AuthorizationController::redirect
