services:
    superlogin.server_manager:
        class: Comolo\SuperLoginClient\ContaoEdition\Foundation\Server\ServerManager
        arguments:
            - "@database_connection"
            - "@router"

    superlogin.remote_user:
        class: Comolo\SuperLoginClient\ContaoEdition\Foundation\User\RemoteUserManager
        public: true
        arguments:
            - "@service_container"
            - "@database_connection"
            - "@router"

    Comolo\SuperLoginClient\ContaoEdition\Foundation\Security:
        autowire: true
