services:
    Comolo\SuperLoginClient\ContaoEdition\Foundation\Server\ServerManager:
        public: true
        autowire: true

    Comolo\SuperLoginClient\ContaoEdition\Foundation\User\RemoteUserManager:
        public: true
        autowire: true

    Comolo\SuperLoginClient\ContaoEdition\Foundation\Security\ContaoBackendLogin:
        public: true
        autowire: true
        arguments:
            $contaoUserProvider: '@contao.security.backend_user_provider'

    Comolo\SuperLoginClient\ContaoEdition\Foundation\User\RemoteContaoOAuth2User:
        public: true
        autowire: true

    Comolo\SuperLoginClient\ContaoEdition\Controller\AuthorizationController:
        public: true
        autowire: true
