services:
    superlogin_listener:
        class: Comolo\SuperLoginClient\ContaoEdition\EventListener\SuperLoginListener
        arguments:
            - "@router"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 63 }